# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dinesh Kumar Seru
title: DevOps tooling | Automation Engineer | Test Architect
email: dineshkseru@gmail.com
website: serudinesh.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  serudinesh
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: linkedin.com/in/dinesh-kumar-seru-20884416

# About Section
# about_title: About Me
#about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  A highly skilled software testing professional with over 15 years of experience in end-to-end software testing and test design. Extensive expertise in the waterfall model, Agile, and Scrum methodologies across various industries, including core banking, payments, and deposits. Hands-on experience with tools like TOSCA, Jira, HP ALM, and AS/400. Adept at collaborating with cross-functional and geographically dispersed teams. Strong business domain knowledge in core banking and financial services with exposure to global clients like HSBC, GE Money, and Lloyds. Driven to contribute to organizational growth while continually enhancing technical knowledge.

# I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Core Competencies & Technical Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 
      •	Test Automation: TOSCA, Selenium, Python
      •	Testing Types: API, E2E, Regression, SIT, UAT, User Entitlement, Identity Access Management
      •	Tools: Jira, HP ALM, Postman, Jenkins, Tableau, Data Studio
      •	Programming: Python, SQL, Mainframes, AS/400
      •	Methodologies: Agile (Scrum), Waterfall, CICD Integration, DevOps
      •	Domains: Core Banking, Payments, Retail Banking, Commercial Banking, Credit Cards
      •	Data Visualization: Tableau, Data Studio, Power BI

        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: WB Solutions LLC
        link: https://www.wbsolutions.com/
        # link_text: boringcompany.com
        sub_title: Data Engineer
        caption: May 2022 - Present
        quote: >
          #Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            •	Led the testing efforts for AAIS, a client-server application supporting new PCRs, with automation using TOSCA.
            •	Integrated Jenkins for DevOps and CI/CD pipelines with TOSCA, enhancing test execution efficiency.
            •	Managed end-to-end testing lifecycle using Jira for user stories, defect tracking, and traceability.
      - layout: left
        title: HSBC Software Development India Pvt. Ltd., Hyderabad
        link: https://www.hsbc.co.in/
        # link_text: boringcompany.com
        sub_title: Senior Consultant Specialist
        caption: Oct 2009 - May 2022
        quote: >
          #Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            •	Spearheaded testing for core banking applications and worked extensively with the payments domain.
            •	Implemented and managed TOSCA test automation frameworks for core banking projects, including “Greenfield” and “US Facility Misalignment.”
            •	Led large teams in automation and manual testing for high-impact projects, ensuring smooth execution of global migrations and product launches.
              - layout: left
        title: Expleo, Chennai
        link: https://expleo.com/global/en/
        # link_text: boringcompany.com
        sub_title: Software Engineer
        caption: Jan 2007 - Sep 2009
        quote: >
          #Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
•	Contributed to software testing for major banking clients, including First Data and Lloyds Banking Group, focusing on end-to-end scenarios and functional testing.
•	Utilized Vision Plus and AS/400 for test management and quality control.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
